dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install tox-travis
before_script:
  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip && mv chromedriver ./inscrawler/bin/
  - cp ./inscrawler/secret.py.dist ./inscrawler/secret.py
script:
  - tox -e py37
